merge into RATINGS(rating_id, name) values ( 1, 'G' );
merge into RATINGS(rating_id, name) values ( 2, 'PG' );
merge into RATINGS(rating_id, name) values ( 3, 'PG-13' );
merge into RATINGS(rating_id, name) values ( 4, 'R' );
merge into RATINGS(rating_id, name) values ( 5, 'NC-17' );
merge into GENRES(genre_id, name) values ( 1, 'Комедия' );
merge into GENRES(genre_id, name) values ( 2, 'Драма' );
merge into GENRES(genre_id, name) values ( 3, 'Мультфильм' );
merge into GENRES(genre_id, name) values ( 4, 'Триллер' );
merge into GENRES(genre_id, name) values ( 5, 'Документальный' );
merge into GENRES(genre_id, name) values ( 6, 'Боевик' );
merge into EVENT_TYPE(name) values ( 'LIKE' );
merge into EVENT_TYPE(name) values ( 'REVIEW' );
merge into EVENT_TYPE(name) values ( 'FRIEND' );
merge into OPERATION(name) values ('REMOVE');
merge into OPERATION(name) values ('ADD');
merge into OPERATION(name) values ( 'UPDATE' );